# Generated by Django 5.1.6 on 2025-02-25 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='img',
        ),
    ]
